# Generated by Django 4.1.3 on 2022-12-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Uname', models.CharField(blank=True, max_length=100, null=True)),
                ('Pswrd', models.CharField(blank=True, max_length=100, null=True)),
                ('Cnfrm', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
