# Generated by Django 4.1.3 on 2022-12-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0002_catdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catdb',
            old_name='catname',
            new_name='Catname',
        ),
    ]
