# Generated by Django 4.1.3 on 2022-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0003_rename_catname_catdb_catname'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=100, null=True)),
                ('Authname', models.CharField(blank=True, max_length=100, null=True)),
                ('Pdate', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('About', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
