# Generated by Django 4.1.3 on 2022-12-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0004_bookdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdb',
            old_name='bookname',
            new_name='Bookname',
        ),
    ]
