# Generated by Django 4.1.3 on 2023-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayflower', '0005_rename_bookname_bookdb_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
